[dev] Project tech stack
cv-gen-team/cv-gen-fe pull request #118
Opened 2022-10-03 15:42 UTC by twentysixhugs

2022-10-05 14:20 UTC, tatsmaki requested changes

2022-10-05 14:20 UTC, tatsmaki commented on src/components/DynamicFieldset/DynamicFieldset.types.ts
>  export type InputGenericEntry<T> = {
может T & { id: string }
?
entryName звучит как string

2022-10-05 14:20 UTC, tatsmaki commented on src/components/ProjectInfo/components/ProjectInfoForm/ProjectInfoForm.tsx
> +            skillsInForm={getValues().techStack}
не смущает что skillsInForm не будут обновляться?
передай через register или Controller

2022-10-05 14:20 UTC, tatsmaki commented on src/pages/EmployeesPage/pages/EmployeeInfo/components/SkillsInput/SkillsInput.tsx
> +          fieldForValue="entryName"
че за? это в каком объекте такое поле?

2022-10-05 14:20 UTC, tatsmaki commented on src/pages/EmployeesPage/pages/EmployeeInfo/components/SkillsInput/SkillsInput.tsx
> +                possibleValues: Mastery,
какой бонус от группировки в объект, кроме создания нового объекта каждый рендер?

2022-10-06 08:33 UTC, twentysixhugs commented on src/components/DynamicFieldset/DynamicFieldset.types.ts
>  export type InputGenericEntry<T> = {
нет, T это поле в форме

2022-10-06 08:37 UTC, twentysixhugs commented on src/pages/EmployeesPage/pages/EmployeeInfo/components/SkillsInput/SkillsInput.tsx
> +          fieldForValue="entryName"
в availableSkills. Чтобы переиспользовать компонент, я прокидываю имя поля, которое нужно использовать как значение

2022-10-06 08:40 UTC, twentysixhugs commented on src/pages/EmployeesPage/pages/EmployeeInfo/components/SkillsInput/SkillsInput.tsx
> +                possibleValues: Mastery,
в зависимости от того, есть ли этот объект в пропах, компонент либо будет показывать уровень владения (языком, скиллом и т.д.), либо не будет

2022-10-06 08:41 UTC, twentysixhugs commented on src/pages/EmployeesPage/pages/EmployeeInfo/components/SkillsInput/SkillsInput.tsx
> +                possibleValues: Mastery,
просто проверять на наличие трех пропов, хз

2022-10-06 08:46 UTC, twentysixhugs commented on src/pages/EmployeesPage/pages/EmployeeInfo/components/SkillsInput/SkillsInput.tsx
> +                possibleValues: Mastery,
Но да, ты прав. Будет вся форма перерендериваться. Я сделаю два компонента

2022-10-07 17:18 UTC, merged