Feature/user entity
cv-gen-team/cv-gen-fe pull request #36
Opened 2022-08-11 13:47 UTC by twentysixhugs

2022-08-11 14:30 UTC, tatsmaki requested changes

2022-08-11 14:30 UTC, tatsmaki commented on src/graphql/User.ts
> +export interface UserUpdateData {
давай договоримся насчет именования входных аргументов
на беке используется input
на фронте насколько знаю передается объект variables
так что предлагаю либо UpdateUserInput, либо UpdateUserVariables

а вообще CreateUserData === UpdateUserData, так что стоит сократить до UserInput || UserVariables

почему я против Data, не вижу разграничения между входными агрументами и результатом

2022-08-11 14:30 UTC, tatsmaki commented on src/index.tsx
> +const httpLink = createHttpLink({
1) конфигурацию аполло клиента в отдельный файл
2) url бека в .env
3) .env в гитигнор
4) .env.example с пустыми переменными

2022-08-11 14:30 UTC, tatsmaki commented on src/pages/EmployeesPage/EmployeesPage.tsx
> +    refetchQueries: [{ query: GET_USERS }],
как-то неоптимально грузить всех юзеров после удаления одного

2022-08-11 14:30 UTC, tatsmaki commented on src/pages/EmployeesPage/EmployeesPage.tsx
> +    pageContent = "loader";
тернарником в ретурне как-то покороче будет

{loading ? 'loader' : error ? 'error' : <Table />}

если так хочется ифы, предлагаю их и квери вынести в EployeesPageBody

2022-08-11 14:30 UTC, tatsmaki commented on src/pages/EmployeesPage/pages/EmployeeInfo/EmployeeInfo.tsx
> +        query: GET_USERS,
тоже неоптимально

2022-08-11 14:30 UTC, tatsmaki commented on src/pages/EmployeesPage/pages/EmployeeInfo/EmployeeInfo.tsx
> +          profile: {
предлагаю таки профиль целиком хранить в форме
филды могут быть 'profile.first_name'

2022-08-11 14:30 UTC, tatsmaki commented on src/pages/EmployeesPage/pages/EmployeeInfo/helpers.ts
> +  if (!user) return user;
вынь из useMemo
оптимизация не стоит того

2022-08-12 09:26 UTC, twentysixhugs commented on src/graphql/User.ts
> +export interface UserUpdateData {
Сделаю просто отражение того, что бекенде

2022-08-12 10:49 UTC, twentysixhugs commented on src/pages/EmployeesPage/pages/EmployeeInfo/EmployeeInfo.tsx
> +    fetchPolicy: "no-cache",
Иначе апдейт всех юзеров не отображается

2022-08-15 05:30 UTC, tatsmaki commented on src/pages/EmployeesPage/EmployeesPage.tsx
> +      update(cache, { data }) {
давай вынесем операции обновления кеша.
подумай куда лучше, скорее всего использоваться будет не только тут.
мне видится такая структура
src/graphql/user/user.cache.ts
src/graphql/user/user.interface.ts
src/graphql/user/user.queries.ts

2022-08-15 05:32 UTC, tatsmaki commented on src/pages/EmployeesPage/EmployeesPage.tsx
> +      update(cache, { data }) {
если надо будет использовать аргументы, то через замыкание
update: deleteUserCacheUpdate(id)

cosnt deleteUserCacheUpdate = (id: string) => () => {}

2022-08-15 05:33 UTC, tatsmaki commented on src/graphql/User.interfaces.ts
> +interface Profile {
src/graphql/profile/profile.interface.ts

2022-08-15 05:33 UTC, tatsmaki commented on src/graphql/User.interfaces.ts
> +interface Department {
src/graphql/department/department.interface.ts

2022-08-15 09:09 UTC, tatsmaki approved these changes

2022-08-15 09:09 UTC, merged