[dev] Build components for loader, inline errors and error toasts.
cv-gen-team/cv-gen-fe pull request #50
Opened 2022-08-18 12:49 UTC by twentysixhugs

2022-08-18 13:35 UTC, tatsmaki commented on src/components/Loader/Loader.tsx
> +  return <StyledLoader />;
посмотри подходит ли CircularProgress из mui компонентов
обычно его используют как лоадер

2022-08-18 13:39 UTC, tatsmaki commented on src/pages/CvsPage/components/CvInfoUpdatePage/CvInfoUpdatePage.tsx
> +        {serverError && <ErrorToast message={serverError} />}
сделайте глобальный контекст для ошибок в тостах
serverErrors
и контейнер с тостами куда-нибудь в App
надоест же на каждой странице прописывать useState и <ErrorToast />

2022-08-18 13:41 UTC, tatsmaki commented on src/pages/EmployeesPage/EmployeesPage.tsx
> +            tryAgainFn={() => {
инлайн функция

2022-08-18 13:41 UTC, tatsmaki commented on src/pages/EmployeesPage/EmployeesPage.tsx
>  const head = [
надо вынести из компонента

2022-08-18 13:42 UTC, tatsmaki commented on src/pages/EmployeesPage/EmployeesPage.tsx
>      },
в deleteUser не нужен optimisticResponse

2022-08-18 13:44 UTC, tatsmaki commented on src/pages/CvsPage/components/CvInfoUpdatePage/CvInfoUpdatePage.tsx
>    });
зачем тут эффект?
в useQuery вроде же свой лоадер?

2022-08-18 13:46 UTC, tatsmaki commented on src/pages/CvsPage/components/CvInfoUpdatePage/CvInfoUpdatePage.tsx
>    });
cvInfoData ведь обновляется от useQuery
зачем дополнительный стейт?
почему не сразу пропом в компонент?

2022-08-18 13:47 UTC, tatsmaki commented on src/pages/CvsPage/components/CvInfoUpdatePage/CvInfoUpdatePage.tsx
>      // Not a table.
не совсем понимаю зачем было выносить сабмит функцию наверх

2022-08-19 06:45 UTC, twentysixhugs commented on src/pages/CvsPage/components/CvInfoUpdatePage/CvInfoUpdatePage.tsx
>    });
эффект поскольку если два useQuery, то либо писать loader: queryOneLoader, loader: queryTwoLoader, либо сделать один isLoading в стейт и изменять его разными запросами

2022-08-19 06:46 UTC, twentysixhugs commented on src/pages/CvsPage/components/CvInfoUpdatePage/CvInfoUpdatePage.tsx
>      // Not a table.
потому что этот компонент используется в разных местах и сабмит в каждом месте может немного отличаться

2022-08-19 07:46 UTC, twentysixhugs commented on src/pages/CvsPage/components/CvInfoUpdatePage/CvInfoUpdatePage.tsx
>      // Not a table.
и следовать SRP. сверху контейнером фетч, снизу презентейшнл отображение

2022-08-19 08:42 UTC, twentysixhugs commented
TODO: обернуть в юзколбек сабмит хендлеры

2022-08-22 08:20 UTC, tatsmaki requested changes

2022-08-22 08:20 UTC, tatsmaki commented on src/context/ErrorToastStore/ErrorToastStore.tsx
> +  const handleSetError = (message: string) => {
колбек

2022-08-22 08:20 UTC, tatsmaki commented on src/context/ErrorToastStore/ErrorToastStore.tsx
> +        <ErrorToast message={error} />
key

2022-08-22 08:20 UTC, tatsmaki commented on src/pages/EmployeesPage/EmployeesPage.tsx
> +              onDelete={handleItemDelete}
проверь чтобы все функции прокидываемые в таблицу были в колбеках
тут точно стоит так сделать

2022-08-22 12:28 UTC, tatsmaki approved these changes

2022-08-22 12:28 UTC, merged