Feature/proj entity
cv-gen-team/cv-gen-fe pull request #51
Opened 2022-08-19 13:51 UTC by murashkoIl

2022-08-22 08:31 UTC, tatsmaki requested changes

2022-08-22 08:31 UTC, tatsmaki commented on src/components/DatePickerFieldset/DatePickerFieldset.tsx
> +              helperText={!field.value ? required : " "}
helperText={fieldState.error?.message}
error={!!fieldState.error}

2022-08-22 08:31 UTC, tatsmaki commented on src/components/Fieldset/Fieldset.tsx
> +                  error={fieldState.isTouched && !field.value}
same

2022-08-22 08:31 UTC, tatsmaki commented on src/components/ProjectInfo/components/ProjectInfoForm/ProjectInfoForm.tsx
> +            onError={() => {
вроде как на контроллере есть проп rules, и туда пишете любую валидацию
которая сама установит ошибки в formState: { errors }
зачем onError и setError мне максимально не понятно

2022-08-22 08:31 UTC, tatsmaki commented on src/components/ProjectInfo/components/ProjectInfoForm/ProjectInfoForm.tsx
> +            required={"Please, specify the field"}
если это required инпута, то он должен быть boolean
если это required react-hook-form контроллера, то он должен быть в rules

2022-08-22 08:31 UTC, tatsmaki commented on src/pages/ProjectsPage/ProjectsPage.tsx
> +  const handleCreate = () => {
проверьте чтобы в таблицу прокидывались только useCallback-и

2022-08-22 09:28 UTC, murashkoIl commented on src/components/DatePickerFieldset/DatePickerFieldset.tsx
> +              helperText={!field.value ? required : " "}
в helperText как минимум можно оставить || " ", чтобы верстка не прыгала когда поле подсвечивается с ошибкой

2022-08-26 10:19 UTC, tatsmaki approved these changes

2022-08-26 10:19 UTC, merged