[dev] Make table searchable
cv-gen-team/cv-gen-fe pull request #63
Opened 2022-08-31 09:36 UTC by twentysixhugs

fix: build scroll inside forms and tables

2022-09-01 07:33 UTC, tuzhyk commented on src/components/Table/Table.tsx
>    const [sortAsc, setSortAsc] = useState(true);
isSortAsc, try to use is prefix with oolean variables

2022-09-01 07:34 UTC, tuzhyk commented on src/components/Table/Table.tsx
> +      {[...items]
why we can't use just items?

2022-09-05 19:07 UTC, tatsmaki requested changes

2022-09-05 19:07 UTC, tatsmaki commented on src/components/Table/Table.tsx
> +                  (key) => typeof key === "string" && key.startsWith(filter),
почему не includes?

2022-09-05 19:07 UTC, tatsmaki commented on src/components/Table/Table.tsx
> +                Object.values(item).some(
зачем искать по всем полям объекта?

2022-09-08 07:45 UTC, twentysixhugs commented on src/components/Table/Table.tsx
> +                Object.values(item).some(
item для, скажем, project, выглядит так:

2022-09-08 13:58 UTC, tuzhyk approved these changes

2022-09-08 16:04 UTC, merged